[package]
name = "pyo3-enum-variant-type"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dev-dependencies]
enum_variant_type = "0.3.1"
trybuild = "1.0.80"

[dependencies]
pyo3 = "0.19.0"
quote = "1.0.29"
syn = { version = "2.0.22", features = ["extra-traits"]}
